### ISSUE TITLE
Docs for actor.getProfile incorrectly indicate that auth is not required

### ISSUE THREAD

**Issue by aidasuhr** [bluesky-social/bsky-docs#100]
Documentation describes the function of endpoint "app.bsky.actor.getProfile" as "Get detailed profile view of an actor. Does not require auth, but contains relevant metadata with auth", however requests not containing a Bearer return 401.

![image](https://github.com/bluesky-social/bsky-docs/assets/57975441/ca46de35-932b-45cd-b0fe-edffb90e5b19)

**Comment by bnewbold** [comment]
The docs aren't very helpful here!

This endpoint, like most (all?) of the `app.bsky` endpoints, is served by the "AppView" (`api.bsky.app` or `public.api.bsky.app`), not by the "PDS" (`bsky.social` or any server like `enoki.us-east.host.bsky.network`). If you are authenticated to the PDS, it will forward the request on to the AppView on your behalf, which is why that works.

For un-authenticated request for public data, you can connect directly to the AppView, eg: `https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor=bnewbold.net`

We should update the docs site to clarify this, and include multiple examples. One complexity is that if you are building a client which *is* authenticated, it is easiest (and best practice) to just have all requests go via the PDS.

**Comment by aidasuhr** [comment]
Ah that makes sense given the architecture! Thanks very much for the clarification.
